#!/usr/bin/env python3
"""Generate tests/fixtures/bamboo_icd/bamboo_icd.urdf (+ viewer copy).

The URDF is the single source of truth for the ICD/LIS bamboo arm's kinematics AND collision
shapes. Every link frame equals the matching Three.js group in Motus.Viewer (mount, j1..j5, jaw),
expressed through one fixed 'pole_hang' joint that maps the viewer's Y-up world onto Motus Z-up
(Motus = Rx(+90deg) * viewer, i.e. viewer (x, y, z) -> Motus (x, -z, y)) and hangs the arm under
the pole at viewer y = 0.40. viewer.js builds its boxes from these same <collision> entries.
"""
import math, pathlib

SEG = [0.030, 0.080, 0.088, 0.088, 0.088, 0.046]
POLE_Y = 0.40
LIM = [(-170, 170), (-90, 90), (-135, 135), (-90, 90), (-170, 170)]
AXES = ["0 1 0", "1 0 0", "1 0 0", "1 0 0", "0 1 0"]
NOMINAL_GL = 24.0   # mm, L-grip opening drawn by default
NOMINAL_GR = 40.0   # mm, R-grip opening drawn by default

def tube(span):
    return (0.012, max(0.008, span - 0.016), 0.016), (0, -span / 2, 0)

def plate_shift(mm):
    return mm / 1000 / 2 + 0.002

def f(v):
    return " ".join(f"{x:.6g}" for x in v)

def box(name, size, xyz, mat):
    return f'''    <visual name="{name}">
      <origin xyz="{f(xyz)}" rpy="0 0 0"/>
      <geometry><box size="{f(size)}"/></geometry>
      <material name="{mat}"/>
    </visual>
    <collision name="{name}">
      <origin xyz="{f(xyz)}" rpy="0 0 0"/>
      <geometry><box size="{f(size)}"/></geometry>
    </collision>
'''

HOUSING_SMALL = (0.046, 0.029, 0.034)
HOUSING_BIG = (0.041, 0.061, 0.040)

links = {}
gl = plate_shift(NOMINAL_GL)
links["mount"] = [
    ("base tube", *tube(SEG[0]), "tube"),
    ("L-grip body", (0.020, 0.016, 0.026), (0, 0.020, 0), "carriage"),
    ("L-grip rail", (0.080, 0.004, 0.004), (0, 0.014, 0), "rail"),
    ("L-grip jaw-", (0.0045, 0.030, 0.024), (-gl, 0, 0), "jaw"),
    ("L-grip jaw+", (0.0045, 0.030, 0.024), (gl, 0, 0), "jaw"),
]
housing = [HOUSING_SMALL, HOUSING_BIG, HOUSING_BIG, HOUSING_BIG, HOUSING_SMALL]
hmat = ["wrist", "elbow", "shoulder", "elbow", "wrist"]
for i in range(4):
    links[f"link_{i+1}"] = [
        (f"θ{i+1}", housing[i], (0, 0, 0), hmat[i]),
        (f"link θ{i+2}", *tube(SEG[i + 1]), "tube"),
    ]
jy = -SEG[5]   # jaw group origin in j5 frame
gr = plate_shift(NOMINAL_GR)
links["link_5"] = [
    ("θ5", housing[4], (0, 0, 0), hmat[4]),
    ("neck", (0.012, 0.028, 0.016), (0, -0.024, 0), "tube"),
    ("R-grip carriage", (0.018, 0.018, 0.022), (0, jy + 0.022, 0), "carriage"),
    ("R-grip rail", (0.080, 0.004, 0.004), (0, jy + 0.012, 0), "rail"),
    ("R-grip jaw-", (0.0045, 0.020, 0.022), (-gr, jy + 0.005, 0), "jaw"),
    ("R-grip jaw+", (0.0045, 0.020, 0.022), (gr, jy + 0.005, 0), "jaw"),
]

out = ['<?xml version="1.0" encoding="utf-8"?>',
       '<!-- GENERATED by tools/bamboo/gen_bamboo_urdf.py - edit the generator, not this file. -->',
       '<!-- ICD/LIS bamboo arm hung under the support pole. Motus world is Z-up; link frames equal the',
       '     Motus.Viewer Three.js groups (Y-up) via the fixed pole_hang joint: Motus = Rx(+90deg) * viewer.',
       '     Collision boxes are exactly the drawn boxes (viewer.js builds its meshes from them). -->',
       '<robot name="bamboo_icd">']
for m, rgba in [("tube", "0.545 0.576 0.604 1"), ("wrist", "0.32 0.35 0.38 1"), ("elbow", "0.39 0.42 0.45 1"),
                ("shoulder", "0.56 0.59 0.62 1"), ("carriage", "0.29 0.32 0.35 1"), ("rail", "0.72 0.75 0.78 1"),
                ("jaw", "0.235 0.267 0.298 1")]:
    out.append(f'  <material name="{m}"><color rgba="{rgba}"/></material>')
out.append('  <!-- World origin on the ground (viewer y = 0). Environment (pole, strut, ground) is a Motus CollisionScene. -->')
out.append('  <link name="base_link"/>')
out.append(f'''  <!-- viewer mount group: position (0, {POLE_Y}, 0), rotation.y = 90deg; composed with Rx(+90deg) Y-up->Z-up -->
  <joint name="pole_hang" type="fixed">
    <parent link="base_link"/>
    <child link="mount"/>
    <origin xyz="0 0 {POLE_Y}" rpy="{math.pi/2!r} 0 {math.pi/2!r}"/>
  </joint>''')

def link_xml(name):
    s = f'  <link name="{name}">\n'
    for (n, size, xyz, mat) in links[name]:
        s += box(n, size, xyz, mat)
    return s + '  </link>'

out.append(link_xml("mount"))
parent = "mount"
for i in range(5):
    lo, hi = LIM[i]
    out.append(f'''  <joint name="joint_{i+1}" type="revolute">
    <parent link="{parent}"/>
    <child link="link_{i+1}"/>
    <origin xyz="0 {-SEG[i]:.6g} 0" rpy="0 0 0"/>
    <axis xyz="{AXES[i]}"/>
    <limit lower="{math.radians(lo):.6f}" upper="{math.radians(hi):.6f}" effort="10" velocity="2.0"/>
  </joint>''')
    out.append(link_xml(f"link_{i+1}"))
    parent = f"link_{i+1}"
out.append(f'''  <!-- Jaw / TCP frame = viewer jaw group (grasp plane origin). -->
  <joint name="tool_joint" type="fixed">
    <parent link="link_5"/>
    <child link="tool0"/>
    <origin xyz="0 {-SEG[5]:.6g} 0" rpy="0 0 0"/>
  </joint>
  <link name="tool0"/>
</robot>''')

root = pathlib.Path(__file__).resolve().parents[2]
text = "\n".join(out) + "\n"
for p in [root / "tests/fixtures/bamboo_icd/bamboo_icd.urdf",
          root / "src/Motus.Viewer/wwwroot/fixtures/bamboo_icd/bamboo_icd.urdf"]:
    p.write_text(text, encoding="utf-8")
    print("wrote", p)
